### ISSUE TITLE
Fails to load as of lately 

### ISSUE THREAD

**Issue by LDAS337** [1d8/sedoppkit#1]
I am having issues with the script loading with the errors shown below. Is anyone else having issues or is it something in my packages?

root💀kali)-[~/sedoppkit]
└─# python3 doppkit.py
Traceback (most recent call last):
  File "/root/sedoppkit/doppkit.py", line 3, in <module>
    from modules.recon import wigle, news, countyempfinder, payroll, ipinfo, businessSearch, plate, businessSearch, venmo, username, phonenumber, wordpress
  File "/root/sedoppkit/modules/recon/countyempfinder.py", line 2, in <module>
    from bs4 import BeautifulSoup
  File "/usr/local/lib/python3.9/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python3.9/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python3.9/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: module 'html5lib.treebuilders' has no attribute '_base'

**Comment by 1d8** [comment]
That's quite odd, it may be a problem with your packages. When I attempted to run it from another virtual machine with a clean install, the only errors I got were regarding the bs4 module and tabulate module not being installed which is solved by simply running `pip3 install bs4` and `pip3 install tabulate`

**Comment by LDAS337** [comment]
> That's quite odd, it may be a problem with your packages. When I attempted to run it from another virtual machine with a clean install, the only errors I got were regarding the bs4 module and tabulate module not being installed which is solved by simply running `pip3 install bs4` and `pip3 install tabulate`

Thanks for the response and letting me know your findings.  Now its for me to try yo figure out whats going on with my machine.

**Comment by NTheOne2018** [comment]
i got the same problem with the tabulate module, i tried pip3 install tabulate but it still doesnt recognize this module
